person_name = input("Name:")
person_age = input("Age:")
favorite_color = input("Favorite Color:")
mobile_number = input("Mobile number:")
motto_in_life = input("Motto in life:")

print(person_name)
print(person_age)
print(favorite_color)
print(mobile_number)
print(motto_in_life)